### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by namhai923** [namhai923/Bison-Bank-of-Canada#142]
As a user, I should have an account to access the application.

**Comment by LimitlessJesse** [comment]
belongs to #76

**Comment by LimitlessJesse** [comment]
Test Steps: 
Login: Go to http://localhost:3000/login, you can login with "elonmusk@twitter.com"
Create Account: Go to http://localhost:3000/login, hit Create Account under Sign in button.
Fill up with First Name, Last Name, a valid email and an account Balance, then hit Sign Up.
Redirect to account page and account is created.
